var MenuDAO = {
    url:'../controller/ControllerMenu.php',
    xTypeData:'json',
    insert:function(xdata){
        xdata["action"]="insert";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(obj){
                alert(obj);
            }
        });
    },
    update:function(xdata){
        xdata["action"]="update";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(){}
        });
    },
    eliminar:function(xdata){
        xdata["action"]="delete";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(){}
        });
    },
    load:function(){
        $('#listaMenus').jqGrid({
            url:'../controller/ControllerMenu.php',
            datatype:'json',
            gridview:true,
            height:100,
            postData:{action:'jqGridListarMenus'},
            width:500,
            pgbuttons:true,
            colNames:['Id','Menu','Estado','Edit'],
            colModel:[
            {
                name:'id',
                index:'id',
                align:'center',
                width:50
            },

            {
                name:'menu',
                index:'menu',
                align:'center',
                width:150
            },

            {
                name:'estado',
                index:'estado',
                align:'center',
                width:80
            },
            {
                name:'edit',
                index:'edit',
                align:'center',
                width:80
            }
            ],
            rowNum:10,
            rowList:[10,20,30],            
            pager: '#eventMenu',
            viewrecords:true,
            sortname:'menu',
            sortorder:'desc',
            caption: "::Menus::"
        });        
    },
    buscar:function(){}
}