var UrlDAO = {
    url:'../controller/ControllerUrl.php',
    xTypeData:'json',
    insert:function(xdata){
        xdata["action"]="insert";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(obj){
                alert(obj);
            }
        });
    },
    update:function(xdata){
        xdata["action"]="update";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(){}
        });
    },
    eliminar:function(xdata){
        xdata["action"]="delete";
        $.ajax({
            url:this.url,
            type:'POST',
            dataType:this.xTypeData,
            data:xdata,
            beforeSend:function(){},
            success:function(){}
        });
    },
    load:function(){
        $('#listaUrl').jqGrid({
            url:this.url,
            datatype:'json',
            gridview:true,
            height:100,
            postData:{action:'jqGridListarUrl'},
            width:500,
            pgbuttons:true,
            colNames:['Id','Url','Menu','Edit'],
            colModel:[
            {
                name:'id',
                index:'id',
                align:'center',
                width:50
            },

            {
                name:'url',
                index:'url',
                align:'center',
                width:150
            },

            {
                name:'menu',
                index:'menu',
                align:'center',
                width:80
            },
            {
                name:'edit',
                index:'edit',
                align:'center',
                width:80
            }
            ],
            rowNum:10,
            rowList:[10,20,30],
            pager: '#eventUrl',
            viewrecords:true,
            sortname:'url',
            sortorder:'desc',
            caption: ":: Url ::"
        });
    },
    buscar:function(){}
}