<#EXPORTANDO DATOS DE LA BD SQL SERVER A UN ARCHIVO PLANO#>
$a = Get-Date; 														# colocando fecha en una variable
$fecha=$a.ToString("yyyy_MM_dd_HH_mm_ss"); 							# dandole formato a la fecha original 
$pathfile="C:\xampp\htdocs\COB_ANDINA\documents\loaddatocontacto\";    # definiendo la ruta donde lo archivos seran trabajados
$fileancii=$pathfile+"DOCS_ANSI_"+$fecha+".txt"; 					# referencia del archivo ansi
$fileutf8=$pathfile+"DOCS_UTF8_"+$fecha+".txt"; 					# referencia del archivo utf-8
$namefile="DOCS_UTF8_"+$fecha+".txt";								# solo el nombre del archivo final
bcp " 	

		SELECT 

		'COD_CLIENTE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION','CORREO','TELEFONO','TIPO_DATO'

		UNION ALL
		
		SELECT
		V.COD_CLIENTE,
		CASE COD
						WHEN '0002' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0002CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0005' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0005CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0003' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0003CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0006' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0006CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0004' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0004CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0007' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0007CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0009' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0009CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0016' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0016CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
						WHEN '0017' THEN (SELECT LTRIM(RTRIM(CL_CDEPT)) FROM RSFACCAR..FT0017CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
		ELSE ''
		END AS 'DEPARTAMENTO',
		CASE COD
					WHEN '0002' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0002CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0005' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0005CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0003' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0003CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0006' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0006CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0004' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0004CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0007' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0007CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0009' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0009CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0016' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0016CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0017' THEN (SELECT LTRIM(RTRIM(CL_CPROV)) FROM RSFACCAR..FT0017CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)

		ELSE ''
		END AS 'PROVINCIA',
		CASE COD
						WHEN '0002' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0002TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0005' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0005TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0003' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0003TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0006' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0006TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0004' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0004TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0007' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0007TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0009' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0009TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0016' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0016TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
						WHEN '0017' THEN ((SELECT LTRIM(RTRIM(TG_CDESCRI)) FROM RSFACCAR..AL0017TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=CL_CUBIGEO))
		ELSE ''
		END AS 'DISTRITO',
		CASE COD
					WHEN '0002' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0002CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0005' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0005CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0003' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0003CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0006' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0006CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0004' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0004CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0007' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0007CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0009' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0009CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0016' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0016CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
					WHEN '0017' THEN (SELECT LTRIM(RTRIM(CL_CDIRCLI)) FROM RSFACCAR..FT0017CLIE WHERE CL_CCODCLI = V.COD_CLIENTE)
		ELSE ''
		END AS 'DIRECCION',
		(SELECT STUFF(    (    SELECT CAST(',' AS VARCHAR(MAX)) + B.CORREO    FROM RSFACCAR..EXPTCOR B    WHERE B.CODIGO_CLIENTE = A.CODIGO_CLIENTE    ORDER BY B.CODIGO_CLIENTE    FOR xml path('')    ), 1, 1, '') AS CORREO FROM RSFACCAR..EXPTCOR A WHERE A.CODIGO_CLIENTE = V.COD_CLIENTE GROUP BY A.CODIGO_CLIENTE) AS CORREO,
		(SELECT STUFF(    (    SELECT CAST(',' AS VARCHAR(MAX)) + B.TELEFONO    FROM RSFACCAR..EXPTTELF B    WHERE B.COD_CLIENTE = A.COD_CLIENTE    ORDER BY B.COD_CLIENTE    FOR xml path('')    ), 1, 1, '') AS TELEFONO FROM RSFACCAR..EXPTTELF A WHERE A.COD_CLIENTE = V.COD_CLIENTE GROUP BY A.COD_CLIENTE) AS TELEFONO,
		'DEFAULT' AS TIPO_DATO
		FROM
		RSFACCAR..VIEW_ALL_CLIENT_ACTIVE V
		WHERE COD IN ('0002','0003','0004','0016')

		UNION ALL

		SELECT
		COD_CLIENTE,
		DE_CDEPT AS DEPARTAMENTO,
		DE_CPROV AS PROVINCIA,
		(SELECT REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(TG_CDESCRI)), CHAR(9), ''), CHAR(10), ''), CHAR(13), '') FROM RSFACCAR..AL0002TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=DE_CDISTRI) AS DISTRITO,
		DE_CDIRECC AS DIRECCION,
		'' AS CORREO,
		'' AS TELEFONO,
		'ENTREGA' AS TIPO_DATO
		FROM
		RSFACCAR..VIEW_ALL_CLIENT_ACTIVE INNER JOIN RSFACCAR..FT0002CLID ON COD_CLIENTE=DE_CCODCLI
		WHERE COD IN ('0002')

		UNION ALL

		SELECT
		COD_CLIENTE,
		DE_CDEPT AS DEPARTAMENTO,
		DE_CPROV AS PROVINCIA,
		(SELECT REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(TG_CDESCRI)), CHAR(9), ''), CHAR(10), ''), CHAR(13), '') FROM RSFACCAR..AL0003TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=DE_CDISTRI) AS DISTRITO,
		DE_CDIRECC AS DIRECCION,
		'' AS CORREO,
		'' AS TELEFONO,
		'ENTREGA' AS TIPO_DATO
		FROM
		RSFACCAR..VIEW_ALL_CLIENT_ACTIVE INNER JOIN RSFACCAR..FT0003CLID ON COD_CLIENTE=DE_CCODCLI
		WHERE COD IN ('0003')

		UNION ALL

		SELECT
		COD_CLIENTE,
		DE_CDEPT AS DEPARTAMENTO,
		DE_CPROV AS PROVINCIA,
		(SELECT REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(TG_CDESCRI)), CHAR(9), ''), CHAR(10), ''), CHAR(13), '') FROM RSFACCAR..AL0004TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=DE_CDISTRI) AS DISTRITO,
		DE_CDIRECC AS DIRECCION,
		'' AS CORREO,
		'' AS TELEFONO,
		'ENTREGA' AS TIPO_DATO
		FROM
		RSFACCAR..VIEW_ALL_CLIENT_ACTIVE INNER JOIN RSFACCAR..FT0004CLID ON COD_CLIENTE=DE_CCODCLI
		WHERE COD IN ('0004')

		UNION ALL

		SELECT
		COD_CLIENTE,
		DE_CDEPT AS DEPARTAMENTO,
		DE_CPROV AS PROVINCIA,
		(SELECT REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(TG_CDESCRI)), CHAR(9), ''), CHAR(10), ''), CHAR(13), '') FROM RSFACCAR..AL0016TABL WHERE TG_CCOD='A2' AND TG_CCLAVE=DE_CDISTRI) AS DISTRITO,
		DE_CDIRECC AS DIRECCION,
		'' AS CORREO,
		'' AS TELEFONO,
		'ENTREGA' AS TIPO_DATO
		FROM
		RSFACCAR..VIEW_ALL_CLIENT_ACTIVE INNER JOIN RSFACCAR..FT0016CLID ON COD_CLIENTE=DE_CCODCLI
		WHERE COD IN ('0016')

		UNION ALL

		SELECT 
		RUC AS COD_CLIENTE,
		DEPARTAMENTO,
		PROVINCIA,
		DISTRITO,
		DIRECCION,
		CORREO,
		TELEFONO,
		'DEFAULT'AS TIPO_DATO
		FROM RSFACCAR..BASE_CLIENTE

 " queryout $fileancii -c -T -w -U sa -P Andinars08; # exportando la BD a un .txt con caracter ansi
Get-Content $fileancii | Set-Content -Encoding utf8 $fileutf8; 		# comando para convertir de ansi a utf-8
# Get-Content $fileancii | Set-Content -Encoding Ascii $fileutf8; 	# comando para convertir de ansi a utf-8
# Get-Content $fileancii | Set-Content -Encoding Unicode $fileutf8; 	# comando para convertir de ansi a utf-8
Remove-Item $fileancii;												# eliminado archivo ansi que se creo
<#EJECUTANDO PHP PASANDOLE VARIABLE PARA CONTROLARLO POR BD MYSQL#>
C:\xampp\php\php.exe -f C:\xampp\htdocs\COB_ANDINA\tarea\exportar_datos_contactos.php $namefile >> C:\xampp\htdocs\COB_ANDINA\tarea\exportar_datos_contactos.log