<?php

	
		

			header("Content-disposition: attachment; filename=cabecera.txt");
		    header("Content-type: plain/text");
		    header("Content-Transfer-Encoding: binary");
		    header("Pragma: no-cache");
		    header("Expires: 0"); 

		    echo 'AREA	BANCA	TERRITORIO	COD_OFI	OFICINA	COD_CEN	NOMBRE	CLASIF_ABR_15	CLASIF_MAY_15	MOTIVO	INDICADOR	SEGMENTO	TIPO	DEUDA	GARANTIA	TOTAL_STOCK_PROVISION_DIC_2014	TOTAL_STOCK_PROVISION_ABR_2015	DIFERENCIA_STOCK_PROVISION	CORPORATIVO	GRANDES_EMPRESAS	MEDIANAS_EMPRESAS	PEQUENAS_EMPRESAS	MICROS_EMRPESAS	CONSUMO_TOTAL	CONSUMO_TARJETA	CONSUMO_PRESTAMO	CONSUMO_CONTIAUTO	HIPOTECARIO	VARIACION_ARRASTRE	PRODUCTO_GENERA_ARRASTRE	DIAS_IMPAGO_PRODUCTO_GENERA_ARRASTRE	TIPO_ARRASTRE	TOTAL_VARIACION_PROVISION	DEUDA_VIGENTE__VIGENTE_CON_IMPAGO	DEUDA_REESTRUCTURADA	DEUDA_REFINANCIADA	DEUDA_VENCIDA	DEUDA_JUDICIAL';

	
	
?>
